[package]
name = "polyseme-zone-gen"
version = "0.1.0"
authors = ["eater <=@eater.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polyseme = { path = "../polyseme" }
clap = "2.33"